#[cfg(test)]
pub mod testing;

pub mod account;
pub mod account_verification;
pub mod blob;
pub mod cli_backend;
pub mod desktop_backend;
pub mod error;
pub mod fs_utils;
pub mod launcher;
pub mod oauth;
pub mod onboard;
pub mod paths;
pub mod project;
pub mod project_display;
pub mod project_config_rewrite;
pub mod project_helpers;
pub mod project_journal;
pub mod project_lock;
pub mod project_memory;
pub mod project_progress;
pub mod project_repair;
pub mod project_rewrite;
pub mod project_sanitize;
pub mod project_types;
pub mod resolve;
pub mod services;
pub mod session_move;
