//! Canonical agent-instruction snippet that tells Claude Code,
//! Codex, and other tool-using agents how to use the Claudepot MCP
//! memory tools.
//!
//! Owned here in `claudepot-core` so the CLI's
//! `claudepot mcp install-snippet` verb and the Tauri Settings →
//! MCP installer pane both emit the same bytes. Previously each
//! had its own copy and they had drifted within a single release.
//!
//! The version stamp at the top of the body lets us update the
//! snippet over time without leaving the user puzzled about why
//! their `@include`'d copy disagrees with a future installer's
//! output — a regen overwrites in place, and they `@include` from
//! a fixed path.

/// Bump this when the snippet body changes meaningfully. The
/// version stamp is the first comment line of the body.
pub const SNIPPET_VERSION: &str = "1";

/// Returns the canonical instruction snippet body. Pure: no I/O,
/// no env reads.
pub fn snippet_body() -> String {
    format!(
        r#"<!-- claudepot-mcp-instructions v{version} — managed by `claudepot mcp install-snippet` or Claudepot GUI -->

# Claudepot shared memory

You have access to the Claudepot MCP memory server via tools
prefixed `claudepot_*`. Use them. Specifically:

- **At the start of a session in a project**, call
  `claudepot_list_decisions(project_path=cwd(), status="active")`
  and `claudepot_list_memories(scope="project", project_path=cwd())`.
  These return durable facts and design decisions that earlier
  sessions (either yours or another agent's) recorded for this
  project. Treat them as load-bearing context.

- **Before asking the user a question that history might
  answer**, call `claudepot_search_memory(query)` to look for
  prior conversations on the topic. If a hit looks relevant,
  follow up with `claudepot_read_conversation` on its file_path
  to read the excerpt. Cross-harness — Codex transcripts surface
  alongside Claude transcripts.

- **When the user states a durable fact, preference, or pattern**
  ("I always run tests with X", "this project uses Y over Z"),
  call `claudepot_remember(scope="project",
  project_path=cwd(), kind="preference"|"fact"|"pattern"|...,
  content="...", created_by="<your-agent-id>")`. Don't ask for
  permission; you can always archive later if it turns out to be
  wrong.

- **When you commit to a non-trivial design decision** with the
  user (data model choice, library pick, architectural cut),
  call `claudepot_log_decision(project_path=cwd(),
  topic="...", decision="...", rationale="...", created_by="...")`.
  If the new decision replaces an older one, pass `supersedes_id`.

- **At the end of an audit / fix loop** where you found and
  resolved problems, call `claudepot_submit_evidence(
  project_path=cwd(), summary="...", verification="...",
  files_changed='["src/a.rs","src/b.rs"]', confidence=N,
  created_by="...")`. Future audit-fix runs in this project will
  see what was already fixed and won't re-litigate.

- **For discovery**, `claudepot_list_sessions(project_path=cwd())`
  and `claudepot_list_projects()` enumerate the cache without
  needing a search query.

All `created_by` ids should identify YOU (e.g.
`codex-cli@2026-05-16`, `claude-code@2026-05-16`,
`<agent-name>@<date>`) so the user can trust the audit trail.

The snippet you're reading is generated by `claudepot mcp
install-snippet` (or by Claudepot's Settings → MCP installer);
running either again refreshes the content. Your CLAUDE.md /
AGENTS.md should `@include` it once and never duplicate it
inline.
"#,
        version = SNIPPET_VERSION,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snippet_body_contains_version_stamp() {
        let body = snippet_body();
        assert!(
            body.starts_with(&format!("<!-- claudepot-mcp-instructions v{SNIPPET_VERSION}")),
            "snippet must start with the version-stamped comment line"
        );
    }

    #[test]
    fn snippet_body_names_canonical_tools() {
        let body = snippet_body();
        for tool in [
            "claudepot_list_decisions",
            "claudepot_list_memories",
            "claudepot_search_memory",
            "claudepot_read_conversation",
            "claudepot_remember",
            "claudepot_log_decision",
            "claudepot_submit_evidence",
            "claudepot_list_sessions",
            "claudepot_list_projects",
        ] {
            assert!(
                body.contains(tool),
                "snippet body must name `{tool}` so agents know it exists"
            );
        }
    }
}
