#!/usr/bin/env bash
# Install this repo's git hooks for the current clone. Idempotent.
#
# ## Why this is more than `ln -sf … .git/hooks/pre-push`
#
# `core.hooksPath` makes git ignore `.git/hooks` **entirely**. It is set
# globally on many machines — the git-lfs installer does it, as do most
# dotfile setups. When it is set, the old one-line symlink install put a
# hook in a directory git never looks at, and printed "Installed" anyway.
#
# That is not hypothetical: it is how the v0.2.7 … v0.2.10 release tags
# were pushed without the Linux/Windows validators in `scripts/pre-push`
# ever running. A silently-inert safety net is worse than none, because
# you stop checking.
#
# ## What this does instead
#
# Points `core.hooksPath` at a repo-local generated directory
# (`.githooks/`, gitignored) — a **--local** setting, so it overrides the
# global one for this clone only and touches no other repo.
#
# Chaining matters: repointing `core.hooksPath` would otherwise disable
# every hook the clone was inheriting. On this machine that includes a
# `commit-msg` hook that strips AI-attribution lines, plus the git-lfs
# family. So the generated hooks run this repo's `scripts/<hook>` first,
# then hand off to the inherited hook. Whatever worked before still works.
#
# Re-running is safe: the inherited path is recorded once in
# `claudepot.inheritedHooksPath` and reused, so a second run cannot
# chain `.githooks/` to itself.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
repo_root="$(pwd)"
ours="$repo_root/.githooks"

# Absolute path, or empty if unset / nonexistent.
abspath() {
  [ -n "${1:-}" ] || return 0
  (cd "$1" 2>/dev/null && pwd) || true
}

current="$(abspath "$(git config --get core.hooksPath || true)")"
if [ "$current" = "$ours" ]; then
  # Re-run: recover the ORIGINAL inherited path, never our own dir.
  inherited="$(git config --get claudepot.inheritedHooksPath || true)"
else
  inherited="$current"
fi
[ -n "$inherited" ] || inherited="$repo_root/.git/hooks"

mkdir -p "$ours"
git config --local claudepot.inheritedHooksPath "$inherited"
git config --local core.hooksPath "$ours"

# --- pre-push: our release validators, then the inherited hook --------
# git feeds the ref list on stdin and BOTH consumers need to read it, so
# buffer once and replay. (git-lfs pre-push reads stdin too; without the
# replay whichever ran second would see EOF and silently do nothing.)
cat > "$ours/pre-push" <<'SHIM'
#!/usr/bin/env bash
# GENERATED by scripts/install-hooks.sh — do not edit.
set -euo pipefail
root="$(git rev-parse --show-toplevel)"
inherited="$(git config --get claudepot.inheritedHooksPath || true)"

refs="$(cat)"

if [ -x "$root/scripts/pre-push" ]; then
  printf '%s\n' "$refs" | "$root/scripts/pre-push" "$@"
fi

if [ -n "$inherited" ] && [ -x "$inherited/pre-push" ]; then
  printf '%s\n' "$refs" | "$inherited/pre-push" "$@"
fi
SHIM
chmod +x "$ours/pre-push"

# --- passthrough shims for every other inherited hook -----------------
shimmed=()
if [ -d "$inherited" ]; then
  for src in "$inherited"/*; do
    [ -f "$src" ] && [ -x "$src" ] || continue
    name="$(basename "$src")"
    case "$name" in
      pre-push | *.sample) continue ;;
    esac
    cat > "$ours/$name" <<SHIM
#!/usr/bin/env bash
# GENERATED by scripts/install-hooks.sh — do not edit.
# Passthrough to the '$name' hook this clone inherited before
# core.hooksPath was pointed at .githooks/.
set -euo pipefail
inherited="\$(git config --get claudepot.inheritedHooksPath || true)"
[ -n "\$inherited" ] && [ -x "\$inherited/$name" ] || exit 0
exec "\$inherited/$name" "\$@"
SHIM
    chmod +x "$ours/$name"
    shimmed+=("$name")
  done
fi

# The old install's symlink is now dead weight and actively misleading —
# it looks installed while git ignores the whole directory.
if [ -L "$repo_root/.git/hooks/pre-push" ]; then
  rm -f "$repo_root/.git/hooks/pre-push"
  echo "Removed the stale .git/hooks/pre-push symlink (core.hooksPath supersedes it)."
fi

echo "core.hooksPath -> .githooks (local to this clone)"
echo "  pre-push      -> scripts/pre-push, then the inherited hook"
if [ ${#shimmed[@]} -gt 0 ]; then
  echo "  passthrough   -> ${shimmed[*]}"
fi
echo "  inherited from: $inherited"

if [ ! -f "$repo_root/.validator-hosts" ]; then
  echo
  echo "Note: no .validator-hosts file found. Release-tag pushes will"
  echo "fail until you create one (see the header of scripts/pre-push;"
  echo "real host names live in CLAUDE.local.md)."
fi
