//! Per-automation helper shim.
//!
//! Every scheduler artifact (launchd plist / Task Scheduler XML /
//! systemd service unit) points at this shim instead of `claude`
//! directly. The shim is responsible for:
//!
//! 1. Allocating a unique per-run directory under
//!    `<claudepot_data_dir>/automations/<id>/runs/<RUN_ID>/`.
//! 2. Updating a `runs/.latest` symlink (unix) or last-run pointer
//!    file (Windows) so launchd's `StandardOutPath` indirection
//!    resolves correctly.
//! 3. Spawning `claude -p` with all configured flags, stdin-fed
//!    prompt (base64-decoded to dodge argv-quoting hazards), and
//!    redirected stdout/stderr.
//! 4. Calling back into `claudepot automation _record-run` so a
//!    structured `result.json` is written by Rust, not shell.
//!
//! Two emitters: [`render_unix`] writes a POSIX `run.sh`,
//! [`render_windows`] writes a `run.cmd`. The Rust side knows
//! exactly nothing about the shell beyond what the goldens lock
//! in.

use std::collections::BTreeMap;

use base64::Engine;

use super::types::{Automation, OutputFormat};

/// Inputs that don't live on the [`Automation`] record itself —
/// resolved at shim-render time and passed in. Keeps the renderer
/// pure (testable without touching disk).
#[derive(Debug, Clone)]
pub struct ShimInputs<'a> {
    /// Absolute path to the binary to invoke (e.g. `/usr/local/bin/claude`
    /// or `<claudepot_data_dir>/bin/<route-wrapper>`).
    pub binary_abs_path: &'a str,
    /// Absolute path to the `claudepot` CLI itself, used to call
    /// the hidden `_record-run` subcommand.
    pub claudepot_cli_abs_path: &'a str,
    /// Where this automation's per-run dirs live. Typically
    /// `<claudepot_data_dir>/automations/<id>`.
    pub automation_dir: &'a str,
    /// Default PATH segments materialized inside the shim.
    pub path_segments: &'a [String],
    /// Optional curated env (already validated via `super::env`).
    pub extra_env: &'a BTreeMap<String, String>,
}

/// Render a POSIX shell shim. Caller writes it to `run.sh` with
/// mode 0700.
pub fn render_unix(automation: &Automation, inputs: &ShimInputs<'_>) -> String {
    let prompt_b64 = base64_encode(&automation.prompt);
    let flags = build_cli_flags(automation);
    let path_value = inputs.path_segments.join(":");
    let auto_dir = sh_quote(inputs.automation_dir);
    let bin = sh_quote(inputs.binary_abs_path);
    let cli = sh_quote(inputs.claudepot_cli_abs_path);
    let cwd = sh_quote(&automation.cwd);
    let id = automation.id.to_string();

    let mut env_block = String::new();
    for (k, v) in inputs.extra_env {
        env_block.push_str(&format!("export {}={}\n", k, sh_quote(v)));
    }

    // Single source of truth: every dynamic value goes through
    // `sh_quote` or is a controlled literal.
    format!(
        r#"#!/bin/sh
# claudepot_managed: true
# Generated by Claudepot. Do not edit by hand — changes will be
# overwritten on the next save of this automation.
set -u

AUTO_ID={id}
AUTO_DIR={auto_dir}
RUN_ID="$(date -u +%Y%m%dT%H%M%SZ)-$$"
RUN_DIR="$AUTO_DIR/runs/$RUN_ID"
mkdir -p "$RUN_DIR"
ln -sfn "$RUN_DIR" "$AUTO_DIR/runs/.latest"

export PATH={path_value}
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERM=dumb
{env_block}
cd {cwd}
START_TS=$(date -u +%s)

printf '%s' '{prompt_b64}' | {decode_cmd} \
  | {bin} -p \
{flags} \
  >"$RUN_DIR/stdout.log" 2>"$RUN_DIR/stderr.log"
EXIT=$?
END_TS=$(date -u +%s)

{cli} automation _record-run \
  --automation-id "$AUTO_ID" \
  --run-id "$RUN_ID" \
  --exit "$EXIT" \
  --start "$START_TS" \
  --end "$END_TS" \
  --trigger scheduled || true

exit $EXIT
"#,
        id = id,
        auto_dir = auto_dir,
        path_value = sh_quote(&path_value),
        env_block = env_block,
        cwd = cwd,
        prompt_b64 = prompt_b64,
        decode_cmd = if cfg!(target_os = "macos") {
            "base64 -D"
        } else {
            "base64 -d"
        },
        bin = bin,
        flags = flags.join(" \\\n"),
        cli = cli,
    )
}

/// Render a Windows `cmd` shim. Caller writes it to `run.cmd`.
pub fn render_windows(automation: &Automation, inputs: &ShimInputs<'_>) -> String {
    let prompt_b64 = base64_encode(&automation.prompt);
    let flags = build_cli_flags(automation);
    let path_value = inputs.path_segments.join(";");
    let id = automation.id.to_string();

    let mut env_block = String::new();
    for (k, v) in inputs.extra_env {
        env_block.push_str(&format!("set \"{}={}\"\r\n", k, cmd_escape_value(v)));
    }

    // PowerShell is used solely for base64 decoding (no `base64.exe`
    // in stock Windows). The decoded prompt is piped via stdin to
    // `claude.exe -p`, so argv quoting is avoided entirely.
    let mut s = String::new();
    s.push_str("@echo off\r\n");
    s.push_str(":: claudepot_managed: true\r\n");
    s.push_str(":: Generated by Claudepot. Do not edit by hand.\r\n");
    s.push_str("setlocal EnableDelayedExpansion\r\n");
    s.push_str(&format!("set \"AUTO_ID={id}\"\r\n"));
    s.push_str(&format!(
        "set \"AUTO_DIR={}\"\r\n",
        cmd_escape_value(inputs.automation_dir)
    ));
    s.push_str(
        "for /f \"usebackq delims=\" %%t in (`powershell -NoProfile -Command \
\"[DateTime]::UtcNow.ToString('yyyyMMddTHHmmssZ')\"`) do set \"RUN_ID=%%t-%RANDOM%\"\r\n",
    );
    s.push_str("set \"RUN_DIR=%AUTO_DIR%\\runs\\%RUN_ID%\"\r\n");
    s.push_str("if not exist \"%RUN_DIR%\" mkdir \"%RUN_DIR%\"\r\n");
    s.push_str("> \"%AUTO_DIR%\\runs\\.latest.txt\" echo %RUN_DIR%\r\n");
    s.push_str(&format!(
        "set \"PATH={}\"\r\n",
        cmd_escape_value(&path_value)
    ));
    s.push_str("set \"LANG=en_US.UTF-8\"\r\n");
    s.push_str("set \"LC_ALL=en_US.UTF-8\"\r\n");
    s.push_str("set \"TERM=dumb\"\r\n");
    s.push_str(&env_block);
    s.push_str(&format!(
        "cd /d \"{}\"\r\n",
        cmd_escape_value(&automation.cwd)
    ));
    s.push_str(
        "for /f \"usebackq delims=\" %%t in (`powershell -NoProfile -Command \
\"[int][double]::Parse((Get-Date -UFormat %%s))\"`) do set \"START_TS=%%t\"\r\n",
    );
    s.push_str(&format!(
        "powershell -NoProfile -Command \"[Console]::OpenStandardOutput().Write(\
[Convert]::FromBase64String('{prompt_b64}'),0,[Convert]::FromBase64String('{prompt_b64}').Length)\" \
| \"{bin}\" -p {flags} > \"%RUN_DIR%\\stdout.log\" 2> \"%RUN_DIR%\\stderr.log\"\r\n",
        prompt_b64 = prompt_b64,
        bin = cmd_escape_value(inputs.binary_abs_path),
        flags = flags.join(" "),
    ));
    s.push_str("set \"EXIT=%ERRORLEVEL%\"\r\n");
    s.push_str(
        "for /f \"usebackq delims=\" %%t in (`powershell -NoProfile -Command \
\"[int][double]::Parse((Get-Date -UFormat %%s))\"`) do set \"END_TS=%%t\"\r\n",
    );
    s.push_str(&format!(
        "\"{cli}\" automation _record-run --automation-id \"%AUTO_ID%\" --run-id \"%RUN_ID%\" \
--exit \"%EXIT%\" --start \"%START_TS%\" --end \"%END_TS%\" --trigger scheduled\r\n",
        cli = cmd_escape_value(inputs.claudepot_cli_abs_path),
    ));
    s.push_str("exit /b %EXIT%\r\n");
    s
}

fn build_cli_flags(a: &Automation) -> Vec<String> {
    let mut v: Vec<String> = Vec::new();
    v.push(format!("    --output-format {}", a.output_format.as_cli_flag()));
    if let Some(model) = &a.model {
        v.push(format!("    --model {}", sh_quote(model)));
    }
    v.push(format!(
        "    --permission-mode {}",
        a.permission_mode.as_cli_flag()
    ));
    if let Some(budget) = a.max_budget_usd {
        v.push(format!("    --max-budget-usd {}", budget));
    }
    if let Some(fb) = &a.fallback_model {
        v.push(format!("    --fallback-model {}", sh_quote(fb)));
    }
    if !a.allowed_tools.is_empty() {
        let joined = a.allowed_tools.join(",");
        v.push(format!("    --allowedTools {}", sh_quote(&joined)));
    }
    if let Some(sp) = &a.system_prompt {
        v.push(format!("    --system-prompt {}", sh_quote(sp)));
    }
    if let Some(ap) = &a.append_system_prompt {
        v.push(format!("    --append-system-prompt {}", sh_quote(ap)));
    }
    for d in &a.add_dir {
        v.push(format!("    --add-dir {}", sh_quote(d)));
    }
    if let Some(schema) = &a.json_schema {
        v.push(format!("    --json-schema {}", sh_quote(schema)));
    }
    if a.bare {
        v.push("    --bare".to_string());
    }
    v.push("    -n".to_string());
    v.push(format!("    {}", sh_quote(&a.name)));
    // Output format guards ensure stream-json / json don't lose
    // the result event we parse later.
    if matches!(a.output_format, OutputFormat::StreamJson) {
        v.push("    --include-partial-messages".to_string());
    }
    v
}

/// POSIX-shell-safe single-quote: wrap and double up any `'`.
pub fn sh_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('\'');
    for ch in s.chars() {
        if ch == '\'' {
            out.push_str("'\\''");
        } else {
            out.push(ch);
        }
    }
    out.push('\'');
    out
}

/// CMD value escape. We use double-quoted `set "K=V"` form, so
/// inside the quotes we must escape `%` as `%%` (delayed expansion
/// is on, but the assignment happens before expansion) and refuse
/// the few characters cmd will not let through.
fn cmd_escape_value(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '%' => out.push_str("%%"),
            '"' => out.push_str("\"\""),
            '\r' | '\n' => {} // reject silently — env validator already rejected
            other => out.push(other),
        }
    }
    out
}

fn base64_encode(s: &str) -> String {
    base64::engine::general_purpose::STANDARD.encode(s.as_bytes())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::automations::types::*;
    use chrono::Utc;
    use uuid::Uuid;

    fn auto() -> Automation {
        let now = Utc::now();
        Automation {
            id: Uuid::nil(),
            name: "morning-pr".into(),
            display_name: None,
            description: None,
            enabled: true,
            binary: AutomationBinary::FirstParty,
            model: Some("sonnet".into()),
            cwd: "/Users/me/repo".into(),
            prompt: "summarize today's PRs".into(),
            system_prompt: None,
            append_system_prompt: Some("you are concise".into()),
            permission_mode: PermissionMode::BypassPermissions,
            allowed_tools: vec!["Read".into(), "Bash(git *)".into()],
            add_dir: vec![],
            max_budget_usd: Some(0.5),
            fallback_model: Some("haiku".into()),
            output_format: OutputFormat::Json,
            json_schema: None,
            bare: false,
            extra_env: Default::default(),
            trigger: Trigger::Cron {
                cron: "0 9 * * *".into(),
                timezone: None,
            },
            platform_options: PlatformOptions::default(),
            log_retention_runs: 50,
            created_at: now,
            updated_at: now,
            claudepot_managed: true,
        }
    }

    fn inputs() -> (Vec<String>, BTreeMap<String, String>) {
        (
            vec!["/usr/local/bin".into(), "/opt/homebrew/bin".into()],
            BTreeMap::new(),
        )
    }

    #[test]
    fn unix_shim_contains_required_pieces() {
        let a = auto();
        let (segs, env) = inputs();
        let inp = ShimInputs {
            binary_abs_path: "/usr/local/bin/claude",
            claudepot_cli_abs_path: "/Users/me/.claudepot/bin/claudepot",
            automation_dir: "/Users/me/.claudepot/automations/00000000-0000-0000-0000-000000000000",
            path_segments: &segs,
            extra_env: &env,
        };
        let s = render_unix(&a, &inp);
        assert!(s.starts_with("#!/bin/sh"));
        assert!(s.contains("claudepot_managed: true"));
        assert!(s.contains("set -u"));
        assert!(s.contains("RUN_DIR="));
        assert!(s.contains("--output-format json"));
        assert!(s.contains("--model 'sonnet'"));
        assert!(s.contains("--permission-mode bypassPermissions"));
        assert!(s.contains("--max-budget-usd 0.5"));
        assert!(s.contains("--fallback-model 'haiku'"));
        assert!(s.contains("--allowedTools 'Read,Bash(git *)'"));
        assert!(s.contains("--append-system-prompt 'you are concise'"));
        assert!(s.contains("automation _record-run"));
        // Prompt is delivered via stdin, not argv — must not
        // appear verbatim in the script.
        assert!(!s.contains("summarize today's PRs"));
    }

    #[test]
    fn unix_shim_quotes_single_quotes_safely() {
        let mut a = auto();
        a.cwd = "/path/with 'apostrophe".into();
        let (segs, env) = inputs();
        let inp = ShimInputs {
            binary_abs_path: "/usr/local/bin/claude",
            claudepot_cli_abs_path: "/cli",
            automation_dir: "/auto",
            path_segments: &segs,
            extra_env: &env,
        };
        let s = render_unix(&a, &inp);
        // sh_quote produces '/path/with '\''apostrophe'
        assert!(s.contains("'/path/with '\\''apostrophe'"));
    }

    #[test]
    fn unix_shim_includes_extra_env_export() {
        let a = auto();
        let segs = vec!["/usr/local/bin".to_string()];
        let mut env = BTreeMap::new();
        env.insert("FOO".to_string(), "bar".to_string());
        let inp = ShimInputs {
            binary_abs_path: "/usr/local/bin/claude",
            claudepot_cli_abs_path: "/cli",
            automation_dir: "/auto",
            path_segments: &segs,
            extra_env: &env,
        };
        let s = render_unix(&a, &inp);
        assert!(s.contains("export FOO='bar'"));
    }

    #[test]
    fn windows_shim_contains_required_pieces() {
        let a = auto();
        let (segs, env) = inputs();
        let inp = ShimInputs {
            binary_abs_path: r"C:\Program Files\claude\claude.exe",
            claudepot_cli_abs_path: r"C:\Users\me\.claudepot\bin\claudepot.exe",
            automation_dir: r"C:\Users\me\.claudepot\automations\00000000-0000-0000-0000-000000000000",
            path_segments: &segs,
            extra_env: &env,
        };
        let s = render_windows(&a, &inp);
        assert!(s.starts_with("@echo off\r\n"));
        assert!(s.contains("claudepot_managed: true"));
        assert!(s.contains("setlocal EnableDelayedExpansion"));
        assert!(s.contains("--output-format json"));
        assert!(s.contains("--permission-mode bypassPermissions"));
        assert!(s.contains("automation _record-run"));
        assert!(s.contains("\r\n"), "windows shim must use CRLF");
    }

    #[test]
    fn windows_shim_escapes_percent() {
        let mut a = auto();
        a.cwd = r"C:\percent%dir".into();
        let (segs, env) = inputs();
        let inp = ShimInputs {
            binary_abs_path: r"C:\claude.exe",
            claudepot_cli_abs_path: r"C:\cli.exe",
            automation_dir: r"C:\auto",
            path_segments: &segs,
            extra_env: &env,
        };
        let s = render_windows(&a, &inp);
        assert!(s.contains("C:\\percent%%dir"));
    }

    #[test]
    fn sh_quote_handles_single_quote() {
        assert_eq!(sh_quote("hello"), "'hello'");
        assert_eq!(sh_quote("it's"), "'it'\\''s'");
        assert_eq!(sh_quote(""), "''");
    }
}
