//! Tray icon constants, menu-item IDs, and the `icon_item` builder.
//!
//! Kept separate from `tray.rs` so the builder logic there can focus on
//! menu composition rather than asset wiring. The PNG bytes are baked in
//! at compile time from `src-tauri/icons/menu/` — changes to the source
//! assets require a rebuild.

use tauri::image::Image;
use tauri::menu::{IconMenuItem, IconMenuItemBuilder};
use tauri::{AppHandle, Wry};

// Lucide-sourced glyph icons. Generated by
// `scripts/generate-menu-icons.sh` from `node_modules/lucide-static/`
// at 96px content centered in a 144px transparent canvas, stroke 1.5
// painted `#3a3a3a` (dark gray, ~22% luminance). macOS NSMenu Vibrant
// Light material is a mid-gray (~rgb(160,160,160)); the prior `#888`
// stroke sat nearly on top of that background and read as invisible.
// muda 0.17 doesn't call `setTemplate:YES` on custom bitmaps, so we
// can't auto-tint between Light and Dark — the value here targets
// Light dropdowns. Pair with a light-stroke set + appearance swap if
// Dark-appearance users report low contrast. Re-run the script after
// upgrading `lucide-static` or tweaking the stroke / padding knobs.
pub const ICON_TERMINAL: &[u8] = include_bytes!("../icons/menu/terminal.png");
pub const ICON_DESKTOP: &[u8] = include_bytes!("../icons/menu/desktop.png");
pub const ICON_USER_PLUS: &[u8] = include_bytes!("../icons/menu/user-plus.png");
pub const ICON_REFRESH: &[u8] = include_bytes!("../icons/menu/refresh.png");
pub const ICON_HOME: &[u8] = include_bytes!("../icons/menu/home.png");
pub const ICON_SLIDERS: &[u8] = include_bytes!("../icons/menu/sliders.png");
pub const ICON_CHECK: &[u8] = include_bytes!("../icons/menu/check.png");
pub const ICON_POWER: &[u8] = include_bytes!("../icons/menu/power.png");
pub const ICON_BAR_CHART: &[u8] = include_bytes!("../icons/menu/bar-chart.png");
pub const ICON_BOLT: &[u8] = include_bytes!("../icons/menu/bolt.png");
// `Verify all` carries a badge-check (validity-confirmation glyph),
// keeping it visually distinct from `Sync` (refresh) and `Active` (check).
pub const ICON_BADGE_CHECK: &[u8] = include_bytes!("../icons/menu/badge-check.png");
// `Open Activities` mirrors the sidebar — `NF.dashboard` maps to
// Lucide `Layers`, so the tray uses the same glyph for the same
// destination.
pub const ICON_LAYERS: &[u8] = include_bytes!("../icons/menu/layers.png");
// Per-row glyphs. Usage rows carry a single account-identity anchor
// (circle-user); Live/Activity rows vary by status so the user can
// scan "what's actually happening" from the tray without opening
// the window — play = busy, pause = waiting, dot = idle.
pub const ICON_CIRCLE_USER: &[u8] = include_bytes!("../icons/menu/circle-user.png");
pub const ICON_CIRCLE_PLAY: &[u8] = include_bytes!("../icons/menu/circle-play.png");
pub const ICON_CIRCLE_PAUSE: &[u8] = include_bytes!("../icons/menu/circle-pause.png");
pub const ICON_CIRCLE_DOT: &[u8] = include_bytes!("../icons/menu/circle-dot.png");

// Menu-item IDs. Anything prefixed `tray:` is routed by
// `handle_menu_event` in `tray.rs`.
pub const ID_SHOW: &str = "tray:show";
pub const ID_SETTINGS: &str = "tray:settings";
pub const ID_QUIT: &str = "tray:quit";
pub const ID_ADD: &str = "tray:add-account";
pub const ID_SYNC: &str = "tray:sync-cc";
pub const ID_DESKTOP_BIND: &str = "tray:desktop-bind";
pub const ID_DESKTOP_CLEAR: &str = "tray:desktop-clear";
pub const ID_DESKTOP_RECONCILE: &str = "tray:desktop-reconcile";
pub const ID_DESKTOP_LAUNCH: &str = "tray:desktop-launch";
pub const ID_ACTIVE_DISPLAY: &str = "tray:active-display";
// Distinct IDs for the dual-bound case (CLI ≠ Desktop) so the two
// rows can both live in the menu without an id collision. Both are
// disabled (display-only); the IDs are never matched in
// `handle_menu_event`.
pub const ID_ACTIVE_DISPLAY_CLI: &str = "tray:active-display:cli";
pub const ID_ACTIVE_DISPLAY_DESKTOP: &str = "tray:active-display:desktop";
pub const ID_USAGE_REFRESH: &str = "tray:usage:refresh";
pub const ID_VERIFY_ALL: &str = "tray:verify-all";
pub const ID_ACTIVITIES: &str = "tray:open-activities";

// Prefixes for dynamic per-account / per-session menu items.
pub const PREFIX_CLI: &str = "tray:cli-switch:";
pub const PREFIX_DESKTOP: &str = "tray:desktop-switch:";
/// Prefix for per-session rows in the Live submenu. Suffix is the
/// sessionId — the menu-event handler routes by this prefix and
/// opens the window with that session selected.
pub const PREFIX_LIVE: &str = "tray:live:";

/// Build an icon menu item from pre-rendered PNG bytes.
pub fn icon_item(
    app: &AppHandle,
    id: &str,
    label: &str,
    bytes: &'static [u8],
) -> Result<IconMenuItem<Wry>, String> {
    let img = Image::from_bytes(bytes).map_err(|e| format!("icon {id}: {e}"))?;
    IconMenuItemBuilder::with_id(id, label)
        .icon(img)
        .build(app)
        .map_err(|e| format!("icon item {id}: {e}"))
}
