//! Tray icon constants, menu-item IDs, and the `icon_item` builder.
//!
//! Kept separate from `tray.rs` so the builder logic there can focus on
//! menu composition rather than asset wiring. The PNG bytes are baked in
//! at compile time from `src-tauri/icons/menu/` — changes to the source
//! assets require a rebuild.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::OnceLock;
use tauri::image::Image;
use tauri::menu::{IconMenuItem, IconMenuItemBuilder};
use tauri::{AppHandle, Wry};

/// True when dropdown menus render on a dark material (system
/// appearance = Dark). Written by [`install_menu_appearance_watcher`]
/// (setup + every `ThemeChanged`); read by [`MenuGlyph::image`] at
/// menu-build time, which may run on a tokio worker — hence an atomic
/// instead of an AppKit query (NSApplication is main-thread-only).
static MENU_APPEARANCE_DARK: AtomicBool = AtomicBool::new(false);

/// A tray-menu glyph with one PNG per menu appearance.
///
/// muda 0.19 never calls `setTemplate:YES` on custom menu-item
/// bitmaps (verified against the registry source — `to_nsimage` /
/// `menuitem_set_icon` set the image verbatim), so AppKit can't
/// auto-tint a single bitmap between Light and Dark dropdowns. A
/// dark-gray stroke disappears on a Dark menu and vice versa; the
/// fix is a paired asset set selected per system appearance.
///
/// Decoding is cached per variant in a `OnceLock` — the bytes are
/// compile-time constants, so the decoded RGBA is identical for the
/// process lifetime, and tray rebuilds (live-session churn, account
/// changes, cc_doctor ticks) stop re-parsing ~20 PNGs each time.
pub struct MenuGlyph {
    /// Dark stroke (`#3a3a3a`) — rendered on LIGHT dropdowns.
    dark_stroke: &'static [u8],
    /// Light stroke (`#d0d0d0`) — rendered on DARK dropdowns.
    light_stroke: &'static [u8],
    dark_cache: OnceLock<Image<'static>>,
    light_cache: OnceLock<Image<'static>>,
}

impl MenuGlyph {
    const fn new(dark_stroke: &'static [u8], light_stroke: &'static [u8]) -> Self {
        Self {
            dark_stroke,
            light_stroke,
            dark_cache: OnceLock::new(),
            light_cache: OnceLock::new(),
        }
    }

    /// Decode (or fetch from cache) the variant matching the current
    /// menu appearance. `Image` is a cheap clone — the RGBA buffer is
    /// `Cow`-owned and clone shares no NSImage state.
    pub fn image(&self) -> Result<Image<'static>, String> {
        let (bytes, cache) = if MENU_APPEARANCE_DARK.load(Ordering::Relaxed) {
            (self.light_stroke, &self.light_cache)
        } else {
            (self.dark_stroke, &self.dark_cache)
        };
        if let Some(img) = cache.get() {
            return Ok(img.clone());
        }
        let img = Image::from_bytes(bytes).map_err(|e| format!("menu glyph decode: {e}"))?;
        // A racing decode of the same constant bytes is identical;
        // losing the `set` race just means we hand back our copy.
        let _ = cache.set(img.clone());
        Ok(img)
    }
}

/// Seed the appearance flag and keep it current. Call once during
/// setup (main thread), after the main window exists.
///
/// The window's theme tracks the system appearance (nothing in this
/// app overrides the native window theme — the in-app `data-theme`
/// flip is CSS-only), and tray dropdown menus follow the system
/// appearance too, so `WindowEvent::ThemeChanged` is the right
/// cross-platform change signal. On a flip the tray is rebuilt so
/// every glyph swaps to the readable stroke variant.
pub fn install_menu_appearance_watcher(app: &AppHandle) {
    use tauri::Manager;
    let Some(window) = app.get_webview_window("main") else {
        // Test harness / headless: leave the default (light) in place.
        return;
    };
    let dark = matches!(window.theme(), Ok(tauri::Theme::Dark));
    MENU_APPEARANCE_DARK.store(dark, Ordering::Relaxed);

    let app = app.clone();
    window.on_window_event(move |event| {
        if let tauri::WindowEvent::ThemeChanged(theme) = event {
            let dark = matches!(theme, tauri::Theme::Dark);
            let prev = MENU_APPEARANCE_DARK.swap(dark, Ordering::Relaxed);
            if prev != dark {
                let handle = app.clone();
                tauri::async_runtime::spawn(async move {
                    if let Err(e) = crate::tray::rebuild(&handle).await {
                        tracing::warn!("tray rebuild after theme change failed: {e}");
                    }
                });
            }
        }
    });
}

// Lucide-sourced glyph icons. Generated by
// `scripts/generate-menu-icons.sh` from `node_modules/lucide-static/`
// at 96px content centered in a 144px transparent canvas, stroke 1.5.
// Each glyph ships two stroke variants: `{name}.png` (#3a3a3a, ~22%
// luminance — targets Light dropdowns; macOS NSMenu Vibrant Light
// material is a mid-gray ≈ rgb(160,160,160), so the prior `#888`
// stroke read as invisible) and `{name}-light.png` (#d0d0d0 — targets
// Dark dropdowns). `MenuGlyph::image` picks per system appearance.
// Re-run the script after upgrading `lucide-static` or tweaking the
// stroke / padding knobs.
macro_rules! menu_glyph {
    ($name:literal) => {
        MenuGlyph::new(
            include_bytes!(concat!("../icons/menu/", $name, ".png")),
            include_bytes!(concat!("../icons/menu/", $name, "-light.png")),
        )
    };
}

pub static ICON_TERMINAL: MenuGlyph = menu_glyph!("terminal");
pub static ICON_DESKTOP: MenuGlyph = menu_glyph!("desktop");
pub static ICON_USER_PLUS: MenuGlyph = menu_glyph!("user-plus");
pub static ICON_REFRESH: MenuGlyph = menu_glyph!("refresh");
pub static ICON_HOME: MenuGlyph = menu_glyph!("home");
pub static ICON_SLIDERS: MenuGlyph = menu_glyph!("sliders");
pub static ICON_CHECK: MenuGlyph = menu_glyph!("check");
pub static ICON_POWER: MenuGlyph = menu_glyph!("power");
pub static ICON_BAR_CHART: MenuGlyph = menu_glyph!("bar-chart");
pub static ICON_BOLT: MenuGlyph = menu_glyph!("bolt");
// `Verify all` carries a badge-check (validity-confirmation glyph),
// keeping it visually distinct from `Sync` (refresh) and `Active` (check).
pub static ICON_BADGE_CHECK: MenuGlyph = menu_glyph!("badge-check");
// `Open Activities` mirrors the sidebar — `NF.dashboard` maps to
// Lucide `Layers`, so the tray uses the same glyph for the same
// destination.
pub static ICON_LAYERS: MenuGlyph = menu_glyph!("layers");
// `Health` — CC self-diagnostic surface. Lucide `shield` rasterized
// at 144×144 to match the rest of the menu glyph set. AppKit treats
// any monochrome glyph in an IconMenuItem the same way regardless
// of color depth; the alpha channel does the work.
pub static ICON_SHIELD: MenuGlyph = menu_glyph!("shield");
// Per-row glyphs. Usage rows carry a single account-identity anchor
// (circle-user); Live/Activity rows vary by status so the user can
// scan "what's actually happening" from the tray without opening
// the window — play = busy, pause = waiting, dot = idle.
pub static ICON_CIRCLE_USER: MenuGlyph = menu_glyph!("circle-user");
pub static ICON_CIRCLE_PLAY: MenuGlyph = menu_glyph!("circle-play");
pub static ICON_CIRCLE_PAUSE: MenuGlyph = menu_glyph!("circle-pause");
pub static ICON_CIRCLE_DOT: MenuGlyph = menu_glyph!("circle-dot");

// Menu-item IDs. Anything prefixed `tray:` is routed by
// `handle_menu_event` in `tray.rs`.
pub const ID_SHOW: &str = "tray:show";
pub const ID_SETTINGS: &str = "tray:settings";
pub const ID_QUIT: &str = "tray:quit";
pub const ID_ADD: &str = "tray:add-account";
pub const ID_SYNC: &str = "tray:sync-cc";
pub const ID_DESKTOP_BIND: &str = "tray:desktop-bind";
pub const ID_DESKTOP_CLEAR: &str = "tray:desktop-clear";
pub const ID_DESKTOP_RECONCILE: &str = "tray:desktop-reconcile";
pub const ID_DESKTOP_LAUNCH: &str = "tray:desktop-launch";
pub const ID_ACTIVE_DISPLAY: &str = "tray:active-display";
// Distinct IDs for the dual-bound case (CLI ≠ Desktop) so the two
// rows can both live in the menu without an id collision. Both are
// disabled (display-only); the IDs are never matched in
// `handle_menu_event`.
pub const ID_ACTIVE_DISPLAY_CLI: &str = "tray:active-display:cli";
pub const ID_ACTIVE_DISPLAY_DESKTOP: &str = "tray:active-display:desktop";
pub const ID_USAGE_REFRESH: &str = "tray:usage:refresh";
pub const ID_VERIFY_ALL: &str = "tray:verify-all";
pub const ID_ACTIVITIES: &str = "tray:open-activities";
pub const ID_HEALTH: &str = "tray:open-health";

// Prefixes for dynamic per-account / per-session menu items.
pub const PREFIX_CLI: &str = "tray:cli-switch:";
pub const PREFIX_DESKTOP: &str = "tray:desktop-switch:";
/// Prefix for per-session rows in the Live submenu. Suffix is the
/// sessionId — the menu-event handler routes by this prefix and
/// opens the window with that session selected.
pub const PREFIX_LIVE: &str = "tray:live:";

/// Build an icon menu item from a pre-rendered glyph pair.
pub fn icon_item(
    app: &AppHandle,
    id: &str,
    label: &str,
    glyph: &'static MenuGlyph,
) -> Result<IconMenuItem<Wry>, String> {
    let img = glyph.image().map_err(|e| format!("icon {id}: {e}"))?;
    IconMenuItemBuilder::with_id(id, label)
        .icon(img)
        .build(app)
        .map_err(|e| format!("icon item {id}: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Both stroke variants of every glyph must decode — a broken or
    /// missing asset should fail in CI, not at menu-build time on a
    /// user's machine (where `icon_item` errors abort the rebuild).
    #[test]
    fn test_menu_glyph_both_variants_decode() {
        let glyphs: [(&str, &MenuGlyph); 17] = [
            ("terminal", &ICON_TERMINAL),
            ("desktop", &ICON_DESKTOP),
            ("user-plus", &ICON_USER_PLUS),
            ("refresh", &ICON_REFRESH),
            ("home", &ICON_HOME),
            ("sliders", &ICON_SLIDERS),
            ("check", &ICON_CHECK),
            ("power", &ICON_POWER),
            ("bar-chart", &ICON_BAR_CHART),
            ("bolt", &ICON_BOLT),
            ("badge-check", &ICON_BADGE_CHECK),
            ("layers", &ICON_LAYERS),
            ("shield", &ICON_SHIELD),
            ("circle-user", &ICON_CIRCLE_USER),
            ("circle-play", &ICON_CIRCLE_PLAY),
            ("circle-pause", &ICON_CIRCLE_PAUSE),
            ("circle-dot", &ICON_CIRCLE_DOT),
        ];
        for (name, glyph) in glyphs {
            assert!(
                Image::from_bytes(glyph.dark_stroke).is_ok(),
                "{name}: dark-stroke PNG failed to decode"
            );
            assert!(
                Image::from_bytes(glyph.light_stroke).is_ok(),
                "{name}: light-stroke PNG failed to decode"
            );
        }
    }

    /// The decode cache must return the same pixel dimensions as a
    /// fresh decode, and repeated calls must keep working (the cache
    /// is shared process state; this also exercises the clone path).
    #[test]
    fn test_menu_glyph_image_caches_and_clones() {
        let first = ICON_CHECK.image().expect("first decode");
        let second = ICON_CHECK.image().expect("cached decode");
        assert_eq!(first.width(), second.width());
        assert_eq!(first.height(), second.height());
        assert_eq!(first.width(), 144, "menu glyphs are 144px canvases");
    }
}
